language: go
sudo: false

matrix:
  include:
  - go: "1.10.x"
  - go: "1.9.x"
  - go: master
  allow_failures:
  - go: master

addons:
  apt:
    update: true

install:
  - go get ./...

script:
  - go build -x
