name: Build
on: [push, pull_request]

jobs:
  build:
    name: Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.15', '1.14' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        shell: bash
        run: go build -x
